/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as UserRepoGitUploadPackRouteImport } from './routes/$user/$repo/git-upload-pack'
import { Route as UserRepoGitReceivePackRouteImport } from './routes/$user/$repo/git-receive-pack'
import { Route as UserRepoInfoRefsRouteImport } from './routes/$user/$repo/info/refs'

const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRepoGitUploadPackRoute = UserRepoGitUploadPackRouteImport.update({
  id: '/$user/$repo/git-upload-pack',
  path: '/$user/$repo/git-upload-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRepoGitReceivePackRoute = UserRepoGitReceivePackRouteImport.update({
  id: '/$user/$repo/git-receive-pack',
  path: '/$user/$repo/git-receive-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRepoInfoRefsRoute = UserRepoInfoRefsRouteImport.update({
  id: '/$user/$repo/info/refs',
  path: '/$user/$repo/info/refs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/todos': typeof TodosRoute
  '/$user/$repo/git-receive-pack': typeof UserRepoGitReceivePackRoute
  '/$user/$repo/git-upload-pack': typeof UserRepoGitUploadPackRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$user/$repo/info/refs': typeof UserRepoInfoRefsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/todos': typeof TodosRoute
  '/$user/$repo/git-receive-pack': typeof UserRepoGitReceivePackRoute
  '/$user/$repo/git-upload-pack': typeof UserRepoGitUploadPackRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$user/$repo/info/refs': typeof UserRepoInfoRefsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/todos': typeof TodosRoute
  '/$user/$repo/git-receive-pack': typeof UserRepoGitReceivePackRoute
  '/$user/$repo/git-upload-pack': typeof UserRepoGitUploadPackRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$user/$repo/info/refs': typeof UserRepoInfoRefsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/todos'
    | '/$user/$repo/git-receive-pack'
    | '/$user/$repo/git-upload-pack'
    | '/api/auth/$'
    | '/$user/$repo/info/refs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/todos'
    | '/$user/$repo/git-receive-pack'
    | '/$user/$repo/git-upload-pack'
    | '/api/auth/$'
    | '/$user/$repo/info/refs'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/todos'
    | '/$user/$repo/git-receive-pack'
    | '/$user/$repo/git-upload-pack'
    | '/api/auth/$'
    | '/$user/$repo/info/refs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  TodosRoute: typeof TodosRoute
  UserRepoGitReceivePackRoute: typeof UserRepoGitReceivePackRoute
  UserRepoGitUploadPackRoute: typeof UserRepoGitUploadPackRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  UserRepoInfoRefsRoute: typeof UserRepoInfoRefsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/$repo/git-upload-pack': {
      id: '/$user/$repo/git-upload-pack'
      path: '/$user/$repo/git-upload-pack'
      fullPath: '/$user/$repo/git-upload-pack'
      preLoaderRoute: typeof UserRepoGitUploadPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/$repo/git-receive-pack': {
      id: '/$user/$repo/git-receive-pack'
      path: '/$user/$repo/git-receive-pack'
      fullPath: '/$user/$repo/git-receive-pack'
      preLoaderRoute: typeof UserRepoGitReceivePackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$user/$repo/info/refs': {
      id: '/$user/$repo/info/refs'
      path: '/$user/$repo/info/refs'
      fullPath: '/$user/$repo/info/refs'
      preLoaderRoute: typeof UserRepoInfoRefsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  TodosRoute: TodosRoute,
  UserRepoGitReceivePackRoute: UserRepoGitReceivePackRoute,
  UserRepoGitUploadPackRoute: UserRepoGitUploadPackRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  UserRepoInfoRefsRoute: UserRepoInfoRefsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
